version: '3.7'
services:
  tarekat-mysql:
    image: mysql:8.0.27
    hostname: tarekat-mysql
    container_name: tarekat-mysql
    environment:
      MYSQL_ROOT_PASSWORD: tarekat
      MYSQL_DATABASE: tarekat
      MYSQL_USER: tarekat
      MYSQL_PASSWORD: tarekat
    ports:
      - "3309:3306"
    expose:
      - 3306
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  tarekat-audit-mysql:
    image: mysql:8.0.27
    hostname: tarekat-audit-mysql
    container_name: tarekat-audit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: tarekat
      MYSQL_DATABASE: tarekat
      MYSQL_USER: tarekat
      MYSQL_PASSWORD: tarekat
    ports:
      - "3307:3306"
    expose:
      - 3306
    volumes:
      - ./data-audit/mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  tarekat-inheritance-mysql:
    image: mysql:8.0.27
    hostname: tarekat-inheritance-mysql
    container_name: tarekat-inheritance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: tarekat
      MYSQL_DATABASE: tarekat
      MYSQL_USER: tarekat
      MYSQL_PASSWORD: tarekat
    ports:
      - "3308:3306"
    expose:
      - 3306
    volumes:
      - ./data-inheritance/mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  tarekat-redis:
    image: redis:latest
    hostname: redis
    container_name: tarekat-redis
    expose:
      - "6379"
  tarekat-memcached:
    image: memcached:1.6.22
    hostname: memcached
    container_name: tarekat-memcached
    expose:
      - "11211"