version: '3.7'
services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    ports:
      - "4444:4444"
    restart: always

  tarekat-redis:
    image: redis:latest
    hostname: redis
    container_name: tarekat-redis
    expose:
      - "6379"