services:
  kabi-server:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: kabi-server
    command: ["runserver"]
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kabi
      POSTGRES_PASSWORD: kabi
      POSTGRES_DB: kabi_db
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
