services:
  kabi-server:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: kabi-server
    command: ["runserver"]
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    stdin_open: true
    tty: true

  celery-worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: celery-worker
    command: ["celery"]
    depends_on:
      - kabi-redis
    volumes:
      - ../:/app
    env_file:
      - ../.env

  celery-beat:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: celery-beat
    command: ["celery-beat"]
    depends_on:
      - kabi-redis
    volumes:
      - ../:/app
    env_file:
      - ../.env